name: Django application workflow

on:
  push:
    branches: [master]

jobs:
  first-job:
    name: Build & Test
    runs-on: windows-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DEBUG: ${{ secrets.DEBUG }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up a Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
