name: Django application workflow

on:
  push:
    branches: [master]

jobs:
  first-job:
    name: Build & Test
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up a Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python manage.py test
