name: Django application workflow

on:
  push:
    branches: [master]

jobs:
  first-job:
    name: Build & Test
    runs-on: windows-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
      DEBUG: ${{ secrets.DEBUG }}
      CORS_ALLOW_ORIGINS: ${{ secrets.CORS_ALLOW_ORIGINS }}
      DATABASE_HOST: ${{ sectets.DATABASE_HOST }}
      DATABASE_NAME: ${{ sectets.DATABASE_NAME }}
      DATABASE_USER: ${{ sectets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ sectets.DATABASE_PASSWORD }}
      DATABASE_PORT: ${{ sectets.DATABASE_PORT }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up a Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test
